[project]
name = "church-automation-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "moviepy>=2.2.1",
    "pathlib>=1.0.1",
    "pathvalidate>=3.3.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["functions*"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
